### ISSUE TITLE
Get rid of PutRtfText and legacy GetRtfText

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#100]
**Is your feature request related to a problem? Please describe.**
Separate RTF files for a StoryBuilder project are an idea from a different era. When even small machines have 4GB or more 
of memory, they serve no practical purpose but do add mind fog to the project. 

**Describe the solution you'd like**
Remove PutRtfText from the code and treat RichEditBox fields like any other text fields in StoryWriter. They will then be read as text fields by StoryReader. However, since existing samples and projects may contain them, provide legacy GetRtfText ability while samples and existing projects are converted before putting a stake through its heart.

**Describe alternatives you've considered**
Leave the code alone (bleh.)

**Additional context**
N/A

**Comment by Rarisma** [comment]
Fixed in #105
