### ISSUE TITLE
ARM64 is broken

### ISSUE THREAD

**Issue by Rarisma** [storybuilder-org/StoryBuilder-2#108]
**Describe the bug**
Terry thinks that ARM64 devices are the way froward with cheap devices, and I can't fault that idea. So we picked a test unit and after testing an ARM64 build on said unit, it didn't load at all with some random error being sent to event viewer which wasn't somthing caused by us but by the architecture. After downgrading to windows 10 and installing it I got the following error
![image](https://user-images.githubusercontent.com/49795711/149195261-605502d0-8977-4ab0-94e4-b86b55eac55e.png)
This shows that somthing is probably getting compiled as x64, not ARM64.

**To Reproduce**
1. install storybuilder on ARM64 device

**Comment by terrycox** [comment]
This issue? 
https://github.com/dotnet/runtime/issues/65263

**Comment by terrycox** [comment]
Per a thread Jake had on the UWP Community Discord, this was filed by Rafael Rivera around 2/12/2022:
https://github.com/dotnet/runtime/issues/65263
It's still showing as new opened, not even triaged yet...

**Comment by terrycox** [comment]
Closed by PR #481
