### ISSUE TITLE
Create issues from elmah.io GitHub app integration

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#132]
**Is your feature request related to a problem? Please describe.**
NLog is now shipping log events to the elmah.io server for error logging. This provides the ability to use advanced elmah.io features. One of these is elmah.io's GitHub App, which can create automatically create GitHub issues from errors logged to elmah.io.

**Describe the solution you'd like**
I'm not sure exactly if or how we should use this. Some of it depends on the information logged. Certainly filtering, perhaps to fatal errors, or for all errors, is desired. Mor research is necessary.

**Describe alternatives you've considered**

**Additional context**
https://docs.elmah.io/elmah-io-apps-github/

**Comment by Rarisma** [comment]
This is fixed.
