### ISSUE TITLE
Generate the StoryBuilder User Manual website from Scrivener

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#139]
This is done, and the manual is available directly [on the web](https://storybuilder-org.github.io/StoryBuilder-2/) and as Help in the program.

**Comment by terrycox** [comment]
Awaiting feedback from the editors as to changes that need to be made to close this.

**Comment by terrycox** [comment]
Layout changes (nesting the lower-level nodes in their parent node) might compress the manual (at least in its online form.)

**Comment by terrycox** [comment]
The storybuilder.org domain is now split from being used as the storybuilder.terrywcox.com website and is a website of its own. The 'Writing with StoryBuilder' blog posts have been moved (the old website was migrated), but no other changes were made.
As a searchable and landing page for StoryBuilder's FOSS software, it needs a website suited to that purpose. One example
is [Project Example](https://github.com/smartergiving/free-nonprofit-starter-website).
The website could also link to other things, such as a video intro to StoryBuilder and the StoryBuilder manual, as well
as to the Microsoft Store (using the Store button) to download it.

**Comment by Rarisma** [comment]
Done.
