### ISSUE TITLE
Implement a Print Manager function for printed reports.

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#157]
**Is your feature request related to a problem? Please describe.**
The ability to select a printer and its options is essential for StoryBuilder print reports.

**Describe the solution you'd like**
A Print Manager dialog should be part of the Print Report menu. 

**Describe alternatives you've considered**
The current mechanism, printing to the default printer, is a work-around but not a long-term solution.

**Additional context**
Here's an example (from Microsoft Edge):
![image](https://user-images.githubusercontent.com/5607778/151010703-d6e66dcb-a12c-45fd-ba28-7fbcb5e1d87b.png)

**Comment by terrycox** [comment]
There is a reported issue with PrintManager:
https://github.com/microsoft/CsWinRT/issues/968
This leads to a ProductBoard voter request:
https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/50-support-printmanager-api?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRjb3hAc3Zzb2Z0LmNvbSIsImlhdCI6MTY0MzYxOTU4NywiZXhwIjoxNjQzNjYyNzg3fQ.QSWHjoHCIpvi0njar6tJ9kgNInE5yTxBatK5zjCWT_Q
A sample of a print dialog in code (for UWP) is at:
https://github.com/microsoft/Windows-universal-samples/blob/main/Samples/Printing/cs/PrintHelper.cs#L171 and L153

**Comment by angelazhangmsft** [comment]
@terrycox - in your scenario, do you need to print a Webview control or other WinUI3 XAML elements?

**Comment by terrycox** [comment]
No, we have text (and .rtf text) entered into forms and formatted into a PrintDocument. That part all works. We need just the classic PrintManger functionality of selecting a destination and printer and its options.

**Comment by angelazhangmsft** [comment]
Thanks! We are looking into migrating the PrintManager functionality to WinUI3. 

We are working on the roadmap for Windows App SDK 1.2 - you're welcome to leave your feedback/vote on the feature here: https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/50-support-printmanager-api

**Comment by Rarisma** [comment]
This has been implemented in #466, however only for windows 11 devices (build 22000 and higher.) as windows 10 appears to not currently support the print manager due to a "bug in the windows 10 print driver". Windows 10 users will see no change in printing.
