### ISSUE TITLE
Sizing issue with Syncfusion ComboBox and compact framework

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#163]
StoryBuilder switched to Syncfusion's WinUI ComboBox to circumvent issues with the Microsoft WInUI Combobox (primarily clipping.) However, the Syncfusion control doesn't honor the compact framework styles dictionary, resulting in less than perfect layout.

**Comment by terrycox** [comment]
Seeing what StoryBuilder looks like without the compact framework (especially with WinUIEx's minimum window size restrictions.)

**Comment by Rarisma** [comment]
Fixed in #166
