### ISSUE TITLE
Purpose of Scene should allow multli-selection

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#165]
**Is your feature request related to a problem? Please describe.**
The Purpose of Scene ComboBox on the Scene story element's Development tab lists a number of things a scene
might (should) accomplish, but currently, only one can be selected. 

**Describe the solution you'd like**
The Syncfusion ComboBox allows multi-selection, and Purpose of Scene should use it.

**Describe alternatives you've considered**
N/A

**Additional context**
This is a feature request, but it's also a bug

**Comment by henley352** [comment]
Tested in new build able tso save all in new project
New Project>added New Scene> selected all to purpose
Saved & Close reopened and scenes display

![image](https://user-images.githubusercontent.com/21226407/156391238-1323de80-c149-4987-8ba1-3ea193681304.png)
