### ISSUE TITLE
If user doesn't select a Sample Story title before selecting Sample button, user is signed out of system 

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#175]
Windows Lenova Laptop

Issue:  
If user doesn't select Sample Stories title before selecting  Sample button, user is signed out of system.

To recreate:
Select Sample stories
Select open samples (without selecting a Story)

Expected results:  pop up message displays, select story to view (or something to that effect)
Actual result:  user is signed out of build- user has to access Storybuilder again

Please see recording:  https://www.loom.com/share/dc2519cfecb247d1adc578204b3a4428

**Comment by Rarisma** [comment]
Cannot replicate this on the latest build of master or 2.0.11

**Comment by henley352** [comment]
Test **Failed** Please see recording (https://www.loom.com/share/8f2713259fca4b1d86a1c9a7df426525)

To Recreate:
From Start, select Storybuilder
Select Sample Stories
Don't select a Story
Select Open Sample button

Story doesn't open, user taken out of Storybuilder as seen in story

**Comment by Rarisma** [comment]
Finally managed to replicate thisl, I am working on a fix now
