### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#183]
**Describe the bug**
Search not working
Per the Storybuilder Manual, the search fields is:  
Search #
[tk TBA - How search works, search text field, the toggle
search button, highlighting Navigation tree nodes]

**To Reproduce**
1. Go to 'search.'
2. Enter text to search for here
3. Enter valid text to search for 'problems'
4. Enter invalid text to search for '#$" 

**Expected behavior**
Valid search - highlights text

Invalid text:
Not found message -similar message to this:  If no search items found

Search results

SEARCH AGAIN
No results found. Please search again or browse our most popular pages:

**Comment by Rarisma** [comment]
After furthing talking with michelle, she was pressing enter instead of search.
No actual bug exists.
