### ISSUE TITLE
Textboxes in dark mode arent rounded and uses black text

### ISSUE THREAD

**Issue by Rarisma** [storybuilder-org/StoryBuilder-2#184]
**Describe the bug**
When dark mode is enabled storybuilder switches the entire UI to become darker, regular WinUI Textboxes switch to white text to make the text readable on a dark background however Extended RTF Textboxes use dark text meaning it practically impossible to read.

**To Reproduce**
1. Enable dark mode
2. Load a story
3. Go to a character and find the appearance catagory

**Expected behavior**
Text becomes white to be readable

**Screenshots**
![image](https://user-images.githubusercontent.com/49795711/155851126-e2708ffa-4d3a-4632-a465-0cdfe3f6ab8f.png)

**Comment by henley352** [comment]
Enable dark mode (Settings>Personalization>Colors (open drop down Dark)

**Comment by henley352** [comment]
Sample Story Snow White >structure tab
outline around viewpoint character dropdown box is not white making it appear like random down arrow

![image](https://user-images.githubusercontent.com/21226407/156370290-afd2262f-502e-400a-839d-b4fe3ae56ce5.png)
