### ISSUE TITLE
Test support email results in address not found

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#188]
**Describe the bug**
Tested email listed in user manual for help- [support@svsoft.com] results in 

Address not foundYour message wasn't delivered to support@svsoft.com because the address couldn't be found, or is unable to receive mail. | Address not foundYour message wasn't delivered to support@svsoft.com because the address couldn't be found, or is unable to receive mail. | Address not found | Your message wasn't delivered to support@svsoft.com because the address couldn't be found, or is unable to receive mail.
-- | -- | -- | --
Address not foundYour message wasn't delivered to support@svsoft.com because the address couldn't be found, or is unable to receive mail. | Address not found | Your message wasn't delivered to support@svsoft.com because the address couldn't be found, or is unable to receive mail.
Address not found
Your message wasn't delivered to support@svsoft.com because the address couldn't be found, or is unable to receive mail.
The response from the remote server was:550 No Such User Here

Address not found
Your message wasn't delivered to [support@svsoft.com]() because the address couldn't be found, or is unable to receive mail.
The response from the remote server was:
550 No Such User Here

**To Reproduce**
1. Go to Chrome email  
2. Enter message
3. to field:  [support@svsoft.com]()
4. receive error

**Expected behavior**
Email is received and responded to.

**Screenshots**
![Screen Shot 2022-02-28 at 6 05 34 PM](https://user-images.githubusercontent.com/21226407/156074715-3844e51f-87a8-48cf-b74f-e7ee73319385.png)

**Comment by henley352** [comment]
Terry advised the following: 
Michelle,  the support@svsoft.com email address is no longer valid; it was changed to support@storybuilder.org.
The repository doc updates were just merged yesterday; that may be where the bad address came from. If anything references support@svsoft.com currently, it's a bug.

Will reopen if encounter reference to other email address.

Sent test email to support@storybuilder.org.

**Comment by Rarisma** [comment]
Sent an email, [support@storybuilder.org](mailto:support@storybuilder.org) works
Might be worth noting that jake@storybuilder.org can also be used if needed

**Comment by terrycox** [comment]
Corrected in Scrivener, \docs and github-pages
