### ISSUE TITLE
Correct misspellings in Sample Stories

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#190]
**Describe the bug**
A scene in Rocky sample story is misspelled.

**To Reproduce**
  

1. From file, select Storybuilder
2. Select Sample Stories
3. Select  <Rocky>
4. Click on open sample button
5. Scroll to scenes, Rocky looses his locker

**Expected behavior**
looses should be loses

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/156265165-3c238db0-340d-497a-b3c1-27e8e5917331.png)

If I encounter any others, I will add to this ticket.

**Comment by henley352** [comment]
Another correction needed extra space - located under scenes

![image](https://user-images.githubusercontent.com/21226407/156266089-025dffdd-0b9a-4d38-aa44-ce846a52ce6e.png)

**Comment by henley352** [comment]
Remove period from scenes to mirror others (no others have period)
![image](https://user-images.githubusercontent.com/21226407/156268490-9f69f7bc-6e7e-430b-a647-fbc3e57a3f6f.png)

**Comment by terrycox** [comment]
Changes per above.

**Comment by henley352** [comment]
Test Passed  loses his locker

![image](https://user-images.githubusercontent.com/21226407/156682629-09311951-2221-42a1-b334-07e3248e29bc.png)

Test Failed: looks like it still has extra space Rocky   awakes
![image](https://user-images.githubusercontent.com/21226407/156683051-c26fda26-a3c8-4bed-a5b1-f6d325cfa58f.png)

Test Failed:  still showing period
![image](https://user-images.githubusercontent.com/21226407/156683467-34a76d58-df7e-4543-89c4-6711de885b9d.png)

Test Passed: Problem instead of Problems https://discord.com/channels/@me/945693033544970320/949055446524780634
