### ISSUE TITLE
Allowing text in date fields & unlimited characters in date fields

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#194]
**Describe the bug**
User is able to type abcdef in date field and in last change field. User is allowed to enter 100 plus characters in those fields.

**To Reproduce**

1. Steps to reproduce the behavior:
2. Start>StoryBuilder
3. Create new story ‘Test2’
4. Select Working Title
5. Click on Story Tab
6. Enter abcdef for date created, last updated field
7. Alt test: enter 100 + characters - allows me to create unlimited amount of text in that field

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/156661248-e9dfd7d6-0219-4e3c-b067-315fbde228ef.png)
![image](https://user-images.githubusercontent.com/21226407/156662169-3cee79da-5ac6-417d-8714-bf5aedcf61e2.png)

**Additional context**

**Comment by Rarisma** [comment]
This is not a bug and its intentional.
