### ISSUE TITLE
Cursor is at /begins at far right in  text box

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#195]
**Describe the bug**
When tabbing into story idea text box, the cursor start far right. Should start far left, beginning of text box.

**To Reproduce**
Start>StoryBuilder
Create new story ‘Test2’
Select Working Title
Click on Story Tab
Tab to date created and last updated field and fill in
Tab to Story idea text box

The cursor should be start far left 

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/156663340-eee4a2f8-c9b9-40a0-a87d-94db45d82c0e.png)

**Comment by henley352** [comment]
In addition, This cursor issues occurs
1.  New character
2.  Role Tab
3.  Tab to Character Sketch text box

Cursor starts far right, should start far left

![image](https://user-images.githubusercontent.com/21226407/156669040-e5e38a3c-1765-4556-825d-f182c6f274d1.png)

**Comment by henley352** [comment]
Also happens in New Character>Physical>Physical Notes - cursor is at far right.
![image](https://user-images.githubusercontent.com/21226407/156672665-29a196da-47aa-4179-808a-3b272bb196ff.png)

**Comment by henley352** [comment]
Same issue new characater>appearance tab>appearance text box

![image](https://user-images.githubusercontent.com/21226407/156673636-c420e9d3-f67c-4a6c-86d6-b3413e17cb59.png)

**Comment by Rarisma** [comment]
This bug appears to affect all extended rich textboxes on release builds only.

**Comment by henley352** [comment]
Test passed confirmed cursor is at beginning 
![image](https://user-images.githubusercontent.com/21226407/158079485-9346c7d4-9b07-4d80-8e89-2d39be2d67e3.png)

**Comment by Rarisma** [comment]
keeping this open for futher investigation.

**Comment by henley352** [comment]
test passed - 
![image](https://user-images.githubusercontent.com/21226407/158079362-8d284c86-75e1-4dd3-a52b-d6863a43fa6d.png)

test failed when I switched display to high contrast.

**Comment by henley352** [comment]
Test failed when i switched display to high contrast 
![image](https://user-images.githubusercontent.com/21226407/158081173-64cf9ced-b079-47f3-b9cd-445453c29c16.png)

**Comment by terrycox** [comment]
Live Visual Tree and Live Property Explorer show TextAlignment as DetectFromContent. According to the description of the TextAlignment enum, 'DetectFromContent is available starting with Windows 10. When the TextAlignment property is set to DetectFromContent, alignment is inferred from the text content of the control. For example, English text is left aligned, and Arabic text is right aligned.'

![2022-03-16_14-14-14](https://user-images.githubusercontent.com/5607778/158659513-36aeab74-eef8-47fb-93ec-19b4254f6f50.png)

**Comment by Rarisma** [comment]
Fixed.
