### ISSUE TITLE
Story Problem drop down in Premise is empty

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#196]
**Describe the bug**
Story Problem drop down in Premise is empty.  (and tip is mispelled)

**To Reproduce**

1. Start>StoryBuilder
2. Create new story ‘Test2’
3. Select Working Title
4. Click on Premise Tab
5. Go to Story Problem dropdown
6. The dropdown is empty
7. Tab to Premise
8. The tip is grammatically incorrect should be Select a Problem not Select a Problems

**Expected behavior**  
Drop Down should show options.  Since I can't select a problem, I can't enter data in premise.

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/156664423-6ddc3cdf-4482-4ff5-a348-45d6d201e281.png)

**Comment by Rarisma** [comment]
The dropdown shows problems in your story, as you have none the dropdown is empty.
The grammar will be fixed soon.
