### ISSUE TITLE
Text Boxes should be same size in New Problem Story Element

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#198]
**Describe the bug**
The 'Conflict' text boxes for Protagonist and Antagonist differ from the text boxes for Problem > Story Question & Resolution>Premise

To Recreate:
Create new story
Add new problem 
click on problem or resolution tab- appears large text box for story question and premise (which looks good) no empty space
click on protagonist or antagonist tab - text box appears small.

**Expected behavior**
For consistency and screen display, text boxes should be same size or close to same size

**Screenshots**
New Problem >Story Question
![image](https://user-images.githubusercontent.com/21226407/156670008-606ab43c-ef05-43d7-9057-cb1d0f97f983.png)

Protagonist> conflict
![image](https://user-images.githubusercontent.com/21226407/156670103-eddbe831-073d-4a19-b367-ea0cb43c479f.png)

Antagonist>conflict
![image](https://user-images.githubusercontent.com/21226407/156670193-3d7053f8-ab32-4def-98f8-96e322f8d6cb.png)

Resolution>premise
![image](https://user-images.githubusercontent.com/21226407/156670292-f4ec61bf-4dc9-4cfd-958a-0e13887ac4fe.png)

**Comment by terrycox** [comment]
ComboBoxes widths are determined largely by the maximum size of the contents. However, any single-line TextBox or ComboBox will expand to hold its contents, unless a specific Width or MaxWidth is specified. RichEditBox fields are the width of the container and all contain scrollbars.

Closing this as a non-bug for now.
