### ISSUE TITLE
If user doesn't select a stock scenes, displays 2 blank stock scenes.

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#214]
If user doesn't select category from stock scenes (from drop down, clicks on stock scenes button, it displays 2 blank stock scenes items.

**To Reproduce**

1. Go to tools>stock scenes
2. don't select any options
3. select stock scenes button
expecting stock scene to either have error message or not post duplicate blank scenes

![image](https://user-images.githubusercontent.com/21226407/158089080-120568ff-066a-41cc-ac35-aee59989f1b7.png)

![image](https://user-images.githubusercontent.com/21226407/158089164-47d3fcf9-baf3-4068-85f4-c29e880a4690.png)

**Expected behavior**
a n error message to select item or error message if no item selected

**Additional context**

**Comment by Rarisma** [comment]
This is the same as #215 and was adressed in bug bash 2 however on a second look the patch was broken, I've addressed this with a PR.
