### ISSUE TITLE
Add elmah.io for NLog logging

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#24]
**Is your feature request related to a problem? Please describe.**

StoryBuilder uses a log file target which logs to the installation's \logs subfolder, but that doesn't help to identify problems remote users are having. elmah.io provides a cloud-based logging service for .NET applications, which allows monitoring remove users' error logs. 

**Describe the solution you'd like**

NLog allows logging to multiple targets. Keep the local log file for all log message levels. The remote logging should just report errors and fatal errors. 

elmah.io is a for-profit service but provides a free service for open-source projects. StoryBuilder must be open-sourced before signing for the no-charge service.

**Describe alternatives you've considered**

More user bug requests, which require contacting the user and retrieving local logs, which then need to be filtered in order to locate the errors.

**Additional context**

https://docs.elmah.io/logging-to-elmah-io-from-nlog/
https://elmah.io/sponsorship/opensource/

**Comment by Rarisma** [comment]
fixed in #133
