### ISSUE TITLE
Suggestion:  Plotting Aids -for consistency put all in ABC order

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#243]
**Describe the bug**
Plotting Aids 2  (Dramatic Situations & Stock Scenes ) are in ABC order.  Master Plots is not.

**To Reproduce**
to reproduce the behavior:
1. Go to tools
2. Click on plotting aids
3. Scroll down to each option as listed above
4.  (Dramatic Situations & Stock Scenes ) are in ABC order.  Master Plots is not

**Expected behavior**
All would mirror each other

**Screenshots**
Master Plots is not in ABC order
![image](https://user-images.githubusercontent.com/21226407/160937192-87892317-4262-4d99-89ff-fb387b174de0.png)

All others are:
Dramatic Situations
![image](https://user-images.githubusercontent.com/21226407/160936393-7ed7f7d8-52c1-4c61-8a27-667b913e5d91.png)

Stock Scenes
![image](https://user-images.githubusercontent.com/21226407/160936559-a7622281-8bef-4514-bf1c-6a3e4f07b437.png)

**Comment by terrycox** [comment]
A note: many of the masterplots are adapted from Ronald Tobias' _20 Master Plots, and how to build them_. Perhaps they should be labeled as such.
