### ISSUE TITLE
Search appears not to be working in Story Narrator View

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#247]
**Describe the problem
Under Notes, I typed notes, search.  Then in Search field, I typed 'notes' then try again with 'search' & clicked on search icon.  Status bar displayed 'Found no matches'

**To Reproduce**
1. Go to '.Story Narrator View..'
2. On Menu Bar, select option to Hide Navigation Pane
3. In Narrative View, Note's section type 'notes, search'
4. In search field, type 'notes', then try again with 'search'
5. Status bar displayed 'Found no matches'

**Expected behavior**
the search text in selected fields will be highlighted 'notes' or 'search'

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/161155920-9888ee2a-82e9-424f-8047-b6429b4244d9.png)

**Additional context**

[updater.2022-03-31.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8393246/updater.2022-03-31.log)

**Comment by henley352** [comment]
Upon further review of help documents, this might be working as expected however it is confusing.

**Comment by Rarisma** [comment]
Working as intended, not everything inside of an element is searched for example scene elements have thier cast members, name, viewpoint character, Protagonist, Antagonist and setting searched.

If we searched every where inside of an element then almost all of them would be hightlighted
