### ISSUE TITLE
Unable to delete the Story Element node (not the root node)

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#248]
**Describe the bug**
Status bar displays 'You can't delete a root node!', when I'm trying to delete a new story element

**To Reproduce**
1. In Story Narrator View, add 2 new sections 
2. Change the 2 section to 'changed name"
3. On navigation pane,  Scroll down to 'changed name' (you'll see blue line)
4. On Menu Bar, select add (+) option
5. Scroll down to 'delete story element'
6.  Select 'delete story element'
7.  Error:  Status bar displays 'You can't delete a root node!'

**Expected behavior**
Story element 'changed name' is deleted and no longer displays on Navigation Pane

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/161159292-7ea911cc-fd13-4774-b22c-80e5f43371b0.png)
![image](https://user-images.githubusercontent.com/21226407/161159603-7cb0056f-55bf-40a8-b061-27386e8ac285.png)

**Additional context**

**Comment by henley352** [comment]
[updater.2022-03-31 notebook640.txt](https://github.com/storybuilder-org/StoryBuilder-2/files/8393460/updater.2022-03-31.notebook640.txt)
I forgot to add log

**Comment by Rarisma** [comment]
Cannot replicate

**Comment by henley352** [comment]
added loom recording https://www.loom.com/share/350e985fdf1c45419927f05f9f3a3a1b
