### ISSUE TITLE
Display issue:  if I maximize my screen & click see more button, the root node is covered by the search field

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#249]
**Describe the bug**
I maximized my screen, then clicked see more button (...) so the labels displayed on the menu bar.  This caused the search field to overlap the root node, 'working title'

**To Reproduce**
1.  Maximize screen
2. In Story Narrator View, Click on 'see more button (...)'
3. Labels display on menu bar
4. Look at Navigation Pane with root node and story elements
5.  Error:  search field overlaps root node

**Expected behavior**
User can clearly view root node

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/161163567-b6a8bf82-16a4-4580-93cd-1568e73b570c.png)

**Additional context**

**Comment by henley352** [comment]
"C:\Users\Jacob\AppData\Local\Packages\3234e32c-9ca1-4ad4-99bc-6583d2362437_q954n8xc8d3cc\RoamingState\Storybuilder\logs\updater.2022-03-31.log"  I forgot to add log.

**Comment by Rarisma** [comment]
Not really a bug.
