### ISSUE TITLE
Conflict builder subcategories & examples are not alphabetized.  Resolution is not alphabetized and is missing a period.

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#250]
**Describe the bug**
Display issue.  All drops downs should mirror others.  
Protagonist >Contact builder>subcategory>is not alphabetized.  
Antagonist>contact builder>example is not alphabetized
Resolution

**To Reproduce**
1. Go to '.New problem..'
2. Click on 'Protagonist....' (follow same steps for  antagonist)
3. Scroll down to 'contact builder....'
4. Select contact builder button
5. error:  not all in alphabetical order, or matching punctuation.

**Expected behavior**
See screen shots below for clear expected behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/161166354-5a0f79e5-a7da-425c-8656-9cadc9149d69.png)
**Conflict categories are alphabetized**
![image](https://user-images.githubusercontent.com/21226407/161166404-c85333ab-5337-468c-bbbb-da61ede00475.png)

**subcategories are not**
![image](https://user-images.githubusercontent.com/21226407/161166480-ee19ab0f-e471-495d-9121-ba2460327ce7.png)

**Examples are**
![image](https://user-images.githubusercontent.com/21226407/161166552-3a063015-2043-496c-b7d4-7fdacf8ff320.png)

**Antagonists >conflict button>subcategories and examples are not in alphabetical order**
![image](https://user-images.githubusercontent.com/21226407/161169032-d8563b5a-6596-45ab-aa91-c505e68321b0.png)

****Resolution**
themes need to be alphabetized
and _______leads to______ needs a period - all others in list have period**
![image](https://user-images.githubusercontent.com/21226407/161168578-0868b9cf-e94d-438f-87e7-6f5244471c7b.png)

**Comment by henley352** [comment]
"C:\Users\Jacob\AppData\Local\Packages\3234e32c-9ca1-4ad4-99bc-6583d2362437_q954n8xc8d3cc\RoamingState\Storybuilder\logs\updater.2022-03-31.log"

**Comment by Rarisma** [comment]
Fixed missing fullstop and conflict builder, alphabetised lists are not a priority or a bug
