### ISSUE TITLE
Log Preferences and Version information to backend server

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#255]
**Is your feature request related to a problem? Please describe.**
We need a data source to maintain a database of installed software users and their choices regarding error logging and receiving a newsletter, as well as which version of StoryBuilder they're running. In other words, we need deployment tracking.

**Describe the solution you'd like**
Have StoryBuilder write records to a JSON or similar file on a backend server. A free server, sponsored by FOSSHost.com, is available for this process.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by Rarisma** [comment]
Done in #261
