### ISSUE TITLE
New Settings element displays starting on 2nd tab- all other elements start on 1st tab

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#263]
**Describe the bug**
New Settings element displays starting on 2nd tab- all other elements start on 1st tab

**To Reproduce**
1.From Start, Go to 'Storybuilder.'
2. Create new story
3. From Navigation pane, add all elements (new folder, new problem, new scene, new setting & new character)
4. Click on each element
5. All elements except new setting tab, page starts on 1st tab

**Expected behavior**
Settings element should start on 1st tab (setting not sensations)

**Screenshots**
1st tab
![image](https://user-images.githubusercontent.com/21226407/161649351-dfa06221-5c0a-4479-933c-fb76e16c5f2c.png)

starts on 2nd tab
![image](https://user-images.githubusercontent.com/21226407/161649444-d42cb6ca-009c-4ee9-992d-bde62b5eca4c.png)

**Additional context**
"C:\Users\Jacob\AppData\Local\Packages\3234e32c-9ca1-4ad4-99bc-6583d2362437_q954n8xc8d3cc\RoamingState\Storybuilder\logs\updater.2022-04-04.log"

**Comment by Rarisma** [comment]
This isnt a bug, the tab is remembered.
This was discussed with michelle
