### ISSUE TITLE
Receiving a message, are you sure you want to empty the trash? for an element that is not in the trash

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#264]
**Describe the bug**
Receiving a message, 'Are you sure you want to empty the trash?'  for an element (folder) that is not in the trash

**To Reproduce**
1. Go to 'Storybuilder & open new story'
2. From navigation paen Add all new elements 'folder, problem, scene, setting  & character'
3. Move folder up and down  (drag and drop a node from place to place)
4. Click on folder
5. Error - receive message 'Are you sure you want to empty the trash?

**Expected behavior**
be able to move the element as it is not in trash can

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/161652002-d58a9d06-977f-4264-975c-6791cdd0c455.png)

**Additional context**
"C:\Users\Jacob\AppData\Local\Packages\3234e32c-9ca1-4ad4-99bc-6583d2362437_q954n8xc8d3cc\RoamingState\Storybuilder\logs\updater.2022-04-04.log"

**Comment by Rarisma** [comment]
User right clicked the trash, not a node
