### ISSUE TITLE
Only able to add one flaw

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#272]
**Describe the bug**
Only able to add one flaw.  If I try and add another flaw, it overwrites the first one.

**To Reproduce**
1. Open an 'existing story...'
2. Add new character
3. Select flaw tab
4. Select flaw builder
5.  Select a flaw 
6. Select a 2nd flaw
7. It overwrites the 1st 

**Expected behavior**
Should be able to add more than one flaw. (confirmed with Terry)

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/161867371-ec7b5bd1-357d-4709-89ba-4466cbb3da4a.png)
![image](https://user-images.githubusercontent.com/21226407/161867439-02b38700-cb64-45a4-b981-9d6f680055cb.png)

**Additional context**
https://www.loom.com/share/4555dbef8aef424db8024fd8487e0658

**Comment by henley352** [comment]
"C:\Users\Jacob\AppData\Local\Packages\3234e32c-9ca1-4ad4-99bc-6583d2362437_q954n8xc8d3cc\RoamingState\Storybuilder\logs\updater.2022-04-05.log"

**Comment by Rarisma** [comment]
This is intentional, the flaw builder is only to give you a basis and will erase the content of flaw textbox when copy flaw example is clicked.
