### ISSUE TITLE
Save Story is not working on existing story 

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#273]
**Describe the bug**
I selected save story however info I entered on new problem and new setting did not save.
**To Reproduce**

1. Go to existing story '.test 4.4.21..'
2. Click on 'new problem then new setting.'
3. Add info to all fields
4. from menu bar, select save story
5. X out
6. Open story builder
7. Open story test 4.4.21

**Expected behavior**
All info entered is saved
**Screenshots**

**Additional context**
"C:\Users\Jacob\AppData\Local\Packages\3234e32c-9ca1-4ad4-99bc-6583d2362437_q954n8xc8d3cc\RoamingState\Storybuilder\logs\updater.2022-04-05.log"

**Comment by henley352** [comment]
[updater.2022-04-05.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8430800/updater.2022-04-05.log)

**Comment by Rarisma** [comment]
Progress tracked on #286.
