### ISSUE TITLE
error message on status bar remains even after user has moved item up or down on navigation pane

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#277]
**Describe the bug**

**To Reproduce**
1. Go to 'new story..'
2. Click on '.external and internal problems.'
3. From Menu Bar, select move down and up
4. when I move down get message - cannot move down further on status bar
5. move up 
6. error:  error cannot move down further remains on status bar

**Expected behavior**
once you move back up - the error remains even after I move back up with arrow

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/162086405-1cd1d9b9-d6ab-4dbe-89db-81c9201a5c3e.png)

**Additional context**
https://www.loom.com/share/231bd624b4a0459f9570e2d9a72eebb0?sharedAppSource=personal_library

[updater.2022-04-06.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8435119/updater.2022-04-06.log)

**Comment by Rarisma** [comment]
The status message remains for a set period of time.
