### ISSUE TITLE
Not adding scene to narrative

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#281]
**Describe the bug**

**To Reproduce**
1. Go to '.new story..'
2. Add New folder, problem, character, setting & scene
3right click on new problem
4. Select add scene to narrative
5.  Error:  scene isn't added [updater.2022-04-07.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8447259/updater.2022-04-07.log)
**Expected behavior**
Scene is added 

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/162331254-d5b34ed6-a2bc-4409-b75a-19167f61a988.png)

**Additional context**
[Add any other context about the problem here.](https://www.loom.com/share/b13e3c9dec34451298475044812aa70e)

**Comment by henley352** [comment]
Loom recording https://www.loom.com/share/b13e3c9dec34451298475044812aa70e?sharedAppSource=personal_library

**Comment by terrycox** [comment]
You can only copy scenes. The Loom video shows you trying to copy a Problem ('?').  The result was a warning message:
![image](https://user-images.githubusercontent.com/5607778/162417496-3c18db65-0087-4167-9a5b-aae941ee7363.png)
