### ISSUE TITLE
Unable to create new story- stuck on project path warning 'You can't put files here!'

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#289]
**Describe the bug**
Unable to create new story- stuck on project path warning 'You can't put files here!'

**To Reproduce**
1. Go to Storybuilder
2. Click on Protoganist & antagonist
3. Select browse 
4. Enter title for new story

**Expected behavior**
Able to enter title and browse will show new story - stuck on warning

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/164993530-8f191e7d-5c7e-4b86-99eb-34ffa14fc51c.png)

**Additional context**

[updater.2022-04-24.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8550402/updater.2022-04-24.log)

**Comment by Rarisma** [comment]
Bugged for that one build, already fixed in master.
