### ISSUE TITLE
create a new story - close story BUT don't save & exit out. (or set timed back ups) - story is still saved

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#297]
**Describe the bug**
create a new story - close story BUT don't save & exit out. (or set timed back ups) - story is still saved

**To Reproduce**
Please see recording https://www.loom.com/share/cd470b0aec404c4fa4d80ad9845e3c55

To recreate:

Create new Problems & Characters story -
External problem>decision>person vs situation
Select Close out of story
then exit out - never saving

NOTE:  I never set up timed backups 
![image](https://user-images.githubusercontent.com/21226407/167516662-a075400a-651a-480b-92c1-b8faab734107.png)

Story is still saved

Beginning of story before new story
**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/167515909-70e3bb55-b012-4a38-bd14-dd65822db460.png)

added new story 
![image](https://user-images.githubusercontent.com/21226407/167516810-875325cc-9bd8-427d-b451-cfaa4bd14dcf.png)

[updater.2022-05-09.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8656050/updater.2022-05-09.log)

**Additional context**

**Comment by Rarisma** [comment]
Not a bug, on creation the story is saved and backed up.
An option to toggle this has been added.
