### ISSUE TITLE
Reports- Choices are not being cleared when I close and reopen the menu

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#305]
**Describe the bug**
The default is the last report selected.  - doesn't clear out after report printed. 

**To Reproduce**

1. Go to 'Reports.'
2. Click on 'Story Synopsis.'
![image](https://user-images.githubusercontent.com/21226407/168426623-7dff969b-acdd-4e39-b528-f420998ead7d.png)
3. Click on Generate Report
4. Click on 'Reports"
5. 'Story Synopsis.' is still checked
![image](https://user-images.githubusercontent.com/21226407/168426623-7dff969b-acdd-4e39-b528-f420998ead7d.png)

**Expected behavior**
Choices are cleared

**Additional context**
[updater.2022-05-14.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8692950/updater.2022-05-14.log)

**Comment by Rarisma** [comment]
Fixed
