### ISSUE TITLE
Premise> Story Problem & Premise not displaying on Report

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#324]
**Describe the bug**
Premise> Story Problem & Premise not displaying on Report

**To Reproduce**
1. Open existing story - The Glass Menagerie
2. From reports, check  story overview & story synopsis
![image](https://user-images.githubusercontent.com/21226407/170369525-0e36bbc1-c918-41e2-9730-7190c6268b95.png)

3.  toggle to story and fill in all premise info
![image](https://user-images.githubusercontent.com/21226407/170370211-33d87256-fd2a-477a-aa8b-a0b1cc5016db.png)
4. Go back to reports,  check  story overview & story synopsis
5. Click on generate report

**Expected behavior**
Report generates with all fields filled in - issue is story problem & premise are not filled in

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/170369063-f78537fe-1913-4dfe-8790-5021b3f05070.png)

**Additional context**

[updater.2022-05-25.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8774641/updater.2022-05-25.log)

**Comment by Rarisma** [comment]
Cannot replicate

**Comment by henley352** [comment]
I'll add a recording tonight

**Comment by Rarisma** [comment]
What version of storybuilder was this done on, that might help track it down

**Comment by henley352** [comment]
The one before the latest- i'll try on the latest one (yesterday's tonight)

**Comment by henley352** [comment]
Still failing problem and premise is not showing on report.
![image](https://user-images.githubusercontent.com/21226407/171296836-14e8b3a8-26bc-44f2-80b8-c973c4eaff6e.png)

[updater.2022-05-31.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8809845/updater.2022-05-31.log)


Premise and 
[tffix2.pdf](https://github.com/storybuilder-org/StoryBuilder-2/files/8809848/tffix2.pdf)

**Comment by Rarisma** [comment]
Can't replicate

**Comment by Rarisma** [comment]
Still can't replicate and neither can michelle, closing
