### ISSUE TITLE
Reports:  Structure> missing viewpoint characters name & text box label doesn't match on report & tone issue

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#325]
**Describe the bug**
 Structure> missing viewpoint characters name & text box label doesn't match on report.  Label says structure notes on storybuilder.  Report shows: style notes.  It should match.  , Finally, tone shows @tonenotes on report.  Three issues.
**To Reproduce**
1. Open existing story - The Glass Menagerie
2. Enter all structure info including viewpoint character
![image](https://user-images.githubusercontent.com/21226407/170371651-7ce36352-47a4-4bf5-8dbf-3af8c017aad4.png))
4. Go back to reports,  check  story overview & story synopsis
5. Click on generate report  viewpoint character Casper Gutman doesn't display on report
6.  In addition,  Label says structure notes on storybuilder.  Report shows: style notes.  It should match
7. Finally, tone shows @tonenotes on report

**Expected behavior**
Report generates with all fields filled in - issue viewpoint character Casper Gutman doesn't display on report
**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/170371461-388c836f-2214-4319-ad96-c8c938663aa3.png)

storybuilder 
![image](https://user-images.githubusercontent.com/21226407/170372564-a1c46fa9-a650-4542-8d8a-274bd4eed55e.png)
report 
![image](https://user-images.githubusercontent.com/21226407/170372699-d76dc5f5-c5c6-4ac8-8775-f273ab6722c6.png)
tone notes
![image](https://user-images.githubusercontent.com/21226407/170373151-c3f53b7d-1a72-465d-a04a-c51410d07a98.png)

**Additional context**
[updater.2022-05-25.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8774732/updater.2022-05-25.log)

**Comment by Rarisma** [comment]
Can't replicate

**Comment by Rarisma** [comment]
This isn't actually whats happening, check #337 for what caused this.
