### ISSUE TITLE
reports>Scenes new cast member not showing on report

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#326]
Describe the bug
Scenes new cast member not showing on report

1. Open existing story - The Glass Menagerie
2.  Select Scene 1 Introduction to Characters
3. Add new character - Jim O'Conner & SAVE
4. Go to reports, check Scenes - & select scene 1
![image](https://user-images.githubusercontent.com/21226407/170375497-caab1722-ed58-49e4-9df7-2d1447f72d91.png)
5.  Generate Reports
6. Click on generate report new character doesn't appear on report

 Expected behavior
All characters appear on report

Screenshots
![image](https://user-images.githubusercontent.com/21226407/170375144-59bf8a98-024c-408d-b6bc-334de7e687ae.png)

[updater.2022-05-25.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8774805/updater.2022-05-25.log)

**Comment by Rarisma** [comment]
According to the log, you may have generated the report and looked at it afterwards
I've tried this myself and it works fine, so can you double check this and record it please

**Comment by henley352** [comment]
I can't recreate the issue either.  I am closing issue.

**Comment by henley352** [comment]
I can't recreate the issue either.  I am closing issue.

**Comment by Rarisma** [comment]
Reopened, can replicate.

See #337 for more info.
