### ISSUE TITLE
The name of the problems does not match the selected problem

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#330]
**Describe the bug**
The name of the problems does not match the selected problem.  The highlighted problem is 'Will Amanda, Laura, and Tom ever be able to escape their constricted lives by living in rather than evading their surroundings?' however the title displays 'Amanda, Laura, and Tom live in fantasy worlds to escape desperate circumstance'

**To Reproduce**
1. Open  'Glass Menagerie'
2. Click on 'Problems>....'s 'Will Amanda, Laura, and Tom ever be able to escape their constricted lives by living in rather than evading their surroundings?
3. Review name 
4. Name shows Amanda, Laura, and Tom live in fantasy worlds to escape desperate circumstance'

**Expected behavior**
Problem and name should match 

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/170580147-eb5fbdac-8499-4237-ab3f-5111d459b7d4.png)

**Additional context**
Tested with this build:  
![image](https://user-images.githubusercontent.com/21226407/170580992-cdd72ca5-370e-4de9-aa5b-3d22d7f3b5a5.png)
[updater.2022-05-26.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8782148/updater.2022-05-26.log)

**Comment by Rarisma** [comment]
whilst this spesific instance has been fixed, this is a very absurd bug.

**Comment by henley352** [comment]
thanks for fixing my absurd bug :-)
