### ISSUE TITLE
Received Syncfusion License error when I clicked on development tab on story narrator view

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#332]
**Describe the bug**
Received Syncfusion License error when I clicked on development tab on story narrator view

**To Reproduce**
1. Go to 'glass menagerie...'
2. Switch to Story Narrator View
3. From Narrator View, select Scene 1
4. Open reports 
5.  From reports, select 1st 3 scenes
![image](https://user-images.githubusercontent.com/21226407/170584624-87a68af6-71cd-42f7-8b98-d5f9f36cc3f0.png)
6.  Generate Report and compare
7.   When I click on Development, I receive error.

**Expected behavior**
no error received

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/170584017-d9a76ce3-e744-42e9-8d36-fdbd8e8d544c.png)

**Additional context**
v2.0.14.28
[updater.2022-05-26.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8782307/updater.2022-05-26.log)

**Comment by Rarisma** [comment]
This has been fixed.
