### ISSUE TITLE
Sequence of report is out of order

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#333]
**Describe the bug**
I selected intro to play, scene 1 and scene 2 & generated report.  Report displays Scene 1, Scene 2 & Intro to play

To Reproduce

1. Go to 'glass menagerie...'
2. Switch to Story Narrator View
3. From Narrator View, select Scene 1
4. Open reports 
5. From reports, select 1st 3 scenes (intro, scene 1 & scene 2)
![image](https://user-images.githubusercontent.com/21226407/170585789-a6618307-6149-4b22-bbf0-68835a9a937b.png)
6.  Generate report - order incorrect Scene1 , Scene2, Intro
[error dev.pdf](https://github.com/storybuilder-org/StoryBuilder-2/files/8782361/error.dev.pdf)

v2.0.14.28

[updater.2022-05-26.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8782344/updater.2022-05-26.log)

**Comment by Rarisma** [comment]
Reports are generated in the order that nodes are selected.
