### ISSUE TITLE
Two new relations issue

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#345]
**Describe the bug**
I opened the Maltese falcon story - added 2 new relationships then when i ran the report the 2 new relationships show on the report but on the screen they do not/no longer show

**To Reproduce**
1. Go to 'Maltese Falcon...'
2. Click on relationships tab 
3. Add 2 new relations Relationship to Sid Wise added | & Relationship to Freed  added | 
[updater.2022-06-07.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8857029/updater.2022-06-07.log)

4. Run report
5. report shows the 2 new relations however the screen relationships characters tab no longer shows them

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/172496294-1a089b0b-a6bf-4b02-a97a-c4d92779db37.png)
 
![image](https://user-images.githubusercontent.com/21226407/172497178-7e68a4b5-0868-4dfb-81a8-b826e72c9530.png)

**Additional context**

**Comment by Rarisma** [comment]
please replicate and record
