### ISSUE TITLE
 [F1] key is not invoking Help

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#347]
**Describe the bug**
Help states:  While the cursor is still on Story Question, try pressing the [F1] key to see what Help looks like. You can invoke Help for any control on any form..

**To Reproduce**
1. Go to 'New Story...'
2. Add new problem
3. Select confict>person vs. person
4. Save
5. Scroll down to Story Question
6. Press  [F1] key 

**Expected behavior**
Help is invoked

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/173194532-64755a9d-3a62-43d5-b624-a00de471dba3.png)

**Additional context**
Version 2.0.15.0
[updater.2022-06-11.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8884244/updater.2022-06-11.log)

**Comment by henley352** [comment]
in addition, Rather than go through the menus, let’s use a shortcut and type in [Ctrl+M]. This will display the Master Plots menu: is not bringing up Master Plots

**Comment by Rarisma** [comment]
F1 doesn't invoke help, the manual is wrong here.
