### ISSUE TITLE
Add an AutoSave feature

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#351]
**Is your feature request related to a problem? Please describe.**
Users can get wrapped up in their creative process and forget simple things like saving their work frequently. We have various backup options, but one feature that would compliment these is an AutoSave feature, which saves the current outline exactly like Save Story / Ctrl+S / Clicking the edit status button. AutoSave's save interval should be saved in  specified in seconds rather than minutes.

**Describe the solution you'd like**
The outline's saved frequently and automatically so work isn't lost.

**Describe alternatives you've considered**
A reminder from time to time to save.

**Additional context**
We should recommend the backup at the start of edit session if AutoSave is selected, so that the user can revert changes back easily if he or she decides they're unwanted.

**Comment by Rarisma** [comment]
Fixed in #357
