### ISSUE TITLE
Relationship is not saving

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#354]
**Describe the bug**
Create a relationship between 'young guy' & 'older woman save using icon- turns green confirmation

**To Reproduce**
1.  Open Storybuilder
2. Click on 'Enter info & save' doc
3. Add new character 'young guy'
4. Add relationship button coworker - see screen shot
5.  Save using icon
6.  Open Storybuilder & enter info & save doc
7. Click on relationship button

**Expected behavior**
info and relationship saved shows - nothing is saved on that tab (see 2nd screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/173461230-6d830659-27dd-4c9a-ab33-9cbf3a440a2e.png)

![image](https://user-images.githubusercontent.com/21226407/173461716-d5ef0f03-8bb9-4aa6-b89c-f4a008a3b521.png)

**Additional context**
v2.0.14.46  
[updater.2022-06-13.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8895072/updater.2022-06-13.log)

**Comment by Rarisma** [comment]
Replicate with video please.

**Comment by henley352** [comment]
while attempting to recreate issue - ran into another issue - see bug https://github.com/storybuilder-org/StoryBuilder-2/issues/356

see recording:  https://www.loom.com/share/de1fa39db17b42fa8dc8aafb2c0b664c

**Comment by Rarisma** [comment]
Fixed in #364
