### ISSUE TITLE
Misspellings in windows store - what's new and feature section

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#369]
**Describe the bug**
Corrections needed in description of new features

**To Reproduce**
1. Go to https://www.microsoft.com/en-us/store/r/storybuilder/9plbnhzv1xm2?rc=1#activetab=pivot:overviewtab
2. Scroll down to 'What's new section' and change 1 to ! (see highlighted screen shot)
3.  Scroll down to 'Features' and correct misspellings outlines and programs
4. See screenshot 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/178109949-f7957d8d-d49d-4e5d-804c-972f08960dc6.png)

**Additional context**

**Comment by henley352** [comment]
Terry fixed this however one additional fix needed.   remove extra space after accessible
![image](https://user-images.githubusercontent.com/21226407/178154437-2869e788-55fa-4be2-a0e6-366443b06082.png)

**Comment by terrycox** [comment]
Closed  per Submission 5 (Release 2.1.1.0)
