### ISSUE TITLE
Allow community to easily recommend documentation changes

### ISSUE THREAD

**Issue by Rarisma** [storybuilder-org/StoryBuilder-2#384]
Some propjects allow editing the documentation page quickly, we should explore this feature to encourage community sourced documentation and fixes.

**Comment by terrycox** [comment]
Edited description to say 'recommend changes' instead of 'make changes.' 

Each page contains an 'Improve this Page' link. We just need to refer to it and how to use it.

**Comment by terrycox** [comment]
Tried but not workable
