### ISSUE TITLE
Remove System.NullReferenceException warnings

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#397]
**Describe the bug**
ReSharper identifies potential NullReferenceException conditions as warnings.

These are often legitimate warnings  and can be addressed in various ways:
- [ Conditional? and ?? expressions]
- [  Add an Assert just prior to the warning (ex., Debug.Assert(user != null); ] 

**To Reproduce**
1 Open StoryBuilder in Visual Studio
2. From the menu, select Extensions | ReSharper | Code Issues in Solution
3. From the Inspection Results panel, check Potential Code Quality Issues for the NullReferenceException warnings

**Expected behavior**
No change in behavior.
These changes require testing.

**Screenshots**
N/A

**Additional context**
[Add any other context about the problem here.](https://stackoverflow.com/questions/4393456/resharper-how-to-remove-possible-system-nullreferenceexception-warning)

**Comment by Rarisma** [comment]
Included in generic code cleanup
