### ISSUE TITLE
Update samples for 2.3 release

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#410]
**Is your feature request related to a problem? Please describe.**
Hamlet.stbx and The Old Man and the Sea.stbx need improvements. Hamlet is missing scene details for 
later scenes; The Old Man and the Sea needs to have its Problems/Scenes rearranged to match the 
'Writing with StoryBuilder' topic 'Plotting with Problems', where it's used as an example.

**Describe the solution you'd like**
Update the two samples to make them more useful.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Rarisma** [comment]
Fixed in #411
