### ISSUE TITLE
Moving a node does not set the change flag

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#412]
**Describe the bug**
If a story node is moved via the Move menu bar commands, the Change flag is not set.

**To Reproduce**
1. Copy a sample to a temporary folder and open it, or create a new outline and add several nodes.
2. Make sure the Change indicator is green.
3. Right-click on a node to move.
4. Launch the Move command from the menu bar.
5. Move the node in any direction.
6. Note that the Change indicator is still green.

**Expected behavior**
Like any change in the outline, the Change indicator should indicate the modification until the outline is 
saved or autosaved.

**Screenshots**
N/A

**Additional context**
This problem will also be true for drag and drop moves, although they currently have other problems.

**Comment by Rarisma** [comment]
Fixed in #413
