### ISSUE TITLE
StoryBuilder version saved in .stbx file is incomplete

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#420]
**Describe the bug**
When a story outline is written by StoryWriter, the first  XMLNode written to the outline is the <StoryBuilder> node.
This node has one attribute, Version. However, the version being written is not the actual version of StoryBuilder
used to write (create or update) the outline doesn't have the actual version of the program, but a literal string:
        _attr.Value = "2.0";
       _stb.Attributes.Append(_attr);
        _xml.AppendChild(_stb);
The actual value would provide verification as to the release of the software used to install a particular feature.

**To Reproduce**
1. Launch StoryBuilder
2. Create a new outline.
3. Close it.
4. Edit the .stbx file for the outline just created from Visual Studio's Open | File command.
5. Locate the <StoryBuilder> node and examine the Version attribute.

**Expected behavior**
The actual version of the software should be displayed.

**Screenshots**
N/A.

**Additional context**
N/A

**Comment by Rarisma** [comment]
Fixed in #469
