### ISSUE TITLE
Exception when updating a Scene from the Story Narrator view

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#427]
A scene's Development tab was edited from the Story Narrator rather than the Story Explorer view. This resulted in a null reference
exception trying to locate the overview Story Element in order to update DateModified. 

**To Reproduce**
1. Open a story containing scenes.
2. Make sure the scene(s) are copied to Narrator View.
3. Switch to Narrator View.
4. Edit one of the scenes.
5. Save the outline.
6. Note the exception.

**Expected behavior**
The changes should be saved. When you switch back to Story Explorer view, if you navigate to the Story Overview, the 
story's date last modified should be the timestamp of the change you save.

**Screenshots**
<img width="1041" alt="2022-10-21_15-30-26" src="https://user-images.githubusercontent.com/5607778/197275149-ac9fae73-536e-4b1f-a1f0-24e28e3b01bc.png">*

**Additional context**
I think this error arises from using DataSource[0] to look for Story Overview, which is only present in Story Explorer. The
code in SaveFile() should refer to StoryModel.StoryExplorer to update the timestamp.

**Comment by Rarisma** [comment]
This has been fixed in a previous revision of StoryBuilder, I believe it was 2.5.1
