### ISSUE TITLE
Purpose of scene rewrite

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#457]
**Describe the bug**
Removing SyncFusion from StoryBuilder requires replacing all SF ComboBoxes with Microsoft's 
WinUI ComboBoxes. However, one control, Scene Purpose on the Scene Tab of the Scene page,
can't be converted in this way because it uses a distinct SyncFusion ComboBox feature, multiple
values. The Microsoft Combobox doesn't support that. 

A solution is to replace the multi-value ComboBox with a (Microsoft) Listview with a data template
that contains a CheckBox. Checked values in the ListViewItems can contain multiple values.
The Cast control in the same Scene Tab uses this approach, and its code can be borrowed for 
Scene Purpose.

**Expected behavior**
The SF ComboBox is no longer used, but the same DataSource binding is maintained and 
multiple values are correctly loaded and saved, and persisted to and from .stbx files.

**Screenshots**
N/A

**Additional context**
The Cast control switches between two lists, 'all characters', to add or remove cast members,
and 'selected cast', just the scene's characters. That's not needed for Scene Purpose; just the
list of all Scene Purpose values is needed.

**Comment by Rarisma** [comment]
Fixed in #464
