### ISSUE TITLE
Error when deleting files

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#462]
**Describe the bug**
Describe the bug
Specified cast is not valid in WriteModel()

elmah.io log data:
Tuesday, December 13, 2022 10:23:12 AM 
Severity: Error
Host: LAPTOP-O6PR5OGM
Type: System.IO.FileNotFoundException
Source: at StoryBuilder.Services.Installation.InstallationService.DeleteFiles()
User: Sean Fager(SeanFager@OUTLOOK.com)
Version: 2.5.1.0

**Expected behavior**

**Screenshots**

**Additional context**
elmah.io log info:
2022-12-13 07:23:05.9835 | Info | Starting Log service |
end

**Comment by terrycox** [comment]
InstallationService has no logging whatsoever. 
Is it possible that ParentFolder is invalid or null?

**Comment by Rarisma** [comment]
Should be fixed in #472
